[package]
name = "aoc-2023"
version = "0.1.0"
edition = "2021"
authors = ["Maia <66437537+maia-s@users.noreply.github.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
opt-level = 3
