[package]
name = "aoc-2024"
version = "0.1.0"
edition = "2021"
authors = ["Maia <66437537+maia-s@users.noreply.github.com>"]

[dependencies]
sha2 = { version = "0.10", default-features = false }
str-block = "0.1"
